variables:
  IMAGE_NAME: "$DOCKER_USER/demo-app"
  IMAGE_TAG: juice-shop-1.1
stages:
  - test
  - build

yarn-test:
  image: node:18-bullseye
  stage: test
  script:
    - yarn install --ignore-engines
    - yarn test

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"