variables:
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  IMAGE_NAME: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/juice-shop-devsecops"

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - ec2
    - shell
  before_script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  script:
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_SHA" -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHA"
    - docker push "$IMAGE_NAME:latest"

deploy_image:
  stage: deploy
  tags:
    - ec2
    - shell
  script:
    - |
      cat > /tmp/ssm-params.json <<EOF
      {
        "commands": [
          "export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION",
          "export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID",
          "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com",
          "docker pull $IMAGE_NAME:latest && (docker stop juice-shop || true) && (docker rm juice-shop || true) && docker run -d --name juice-shop -p 3000:3000 $IMAGE_NAME:latest"
        ]
      }
      EOF
    - COMMAND_ID=$(aws ssm send-command --instance-ids "i-050fc1afeab845e65" --document-name "AWS-RunShellScript" --cli-input-json file:///tmp/ssm-params.json --query "Command.CommandId" --output text)
    - sleep 15
    - aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "i-050fc1afeab845e65"
